name: Build extractor service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: pnpm install
      - run: pnpm --filter ./extractor test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: extractor/Dockerfile
          load: true
          tags: blindern/energi-extractor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push container
        if: github.ref == 'refs/heads/main'
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: extractor/Dockerfile
          push: true
          tags: blindern/energi-extractor:latest

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl --fail -L -i -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST https://deployer.foreningenbs.no/deploy -d '
          {
            "service": "energi-extractor",
            "attributes": {
              "image": "blindern/energi-extractor@${{ steps.docker_build.outputs.digest }}"
            }
          }'
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}
