name: Build extractor service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: pnpm install
      - run: pnpm --filter ./extractor test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: extractor/Dockerfile
          load: true
          tags: ghcr.io/blindern/energi-extractor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push container
        if: github.ref == 'refs/heads/main'
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: extractor/Dockerfile
          push: true
          tags: ghcr.io/blindern/energi-extractor:latest

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl --fail -L -i -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST https://deployer.foreningenbs.no/deploy -d '
          {
            "service": "energi-extractor",
            "attributes": {
              "image": "ghcr.io/blindern/energi-extractor@${{ steps.docker_build.outputs.digest }}"
            }
          }'
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}
